version: '3.8'

services:

  web:
    build: .
    ports:
     - "5000:5000"
    environment:
      - DATABASE=postgresql://postgres:password@db/postgres
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: password
      - POSTGRES_DB: postgres
    volumes:
      - pgdata: /var/lib/postgresql/data
  
volumes:
  pgdata:


# To build this

# docker-compose up --build
# docker-compose down
