version: '3'
services:
  mongodb:
    image: mongo
    ports:
    - 27017:27017 # HOST:container
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
    - mongo-network
  mongo-express:
    image: mongo-express
    ports:
    - 8081:8081
    environment:
    - ME_CONFIG_BASICAUTH_USERNAME=teraxiom
    - ME_CONFIG_BASICAUTH_PASSWORD=teraxiom
    - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
    - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
    - mongo-network

networks:
  mongo-network:
    driver: bridge